cidr_block         = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
availability_zone  = "ap-northeast-1a"
env                = "dev"
app_name           = "myapp"
key_name           = "mrb-key-win"